package agents

import (
	"encoding/json"
	"fmt"
	"regexp"
	"strings"
)

// overviewBody renders the project-facts section shared by every generated
// instruction file: languages, detected build tooling, and top-level layout.
func overviewBody(a Analysis) string {
	var b strings.Builder

	fmt.Fprintf(&b, "## Project: %s\n\n", a.ProjectName)

	if len(a.Languages) > 0 {
		b.WriteString("**Languages:** ")
		names := make([]string, 0, len(a.Languages))
		for i, l := range a.Languages {
			if i >= 5 {
				break
			}
			names = append(names, l.Language)
		}
		b.WriteString(strings.Join(names, ", "))
		b.WriteString("\n\n")
	}

	if len(a.TopLevel) > 0 {
		b.WriteString("**Top-level layout:**\n\n")
		for _, dir := range a.TopLevel {
			fmt.Fprintf(&b, "- `%s/`\n", dir)
		}
		b.WriteString("\n")
	}

	if len(a.Ecosystems) > 0 {
		b.WriteString("**Common commands:**\n\n")
		for _, eco := range a.Ecosystems {
			fmt.Fprintf(&b, "- %s\n", eco.Name)
			if eco.BuildCmd != "" {
				fmt.Fprintf(&b, "  - Build: `%s`\n", eco.BuildCmd)
			}
			if eco.TestCmd != "" {
				fmt.Fprintf(&b, "  - Test: `%s`\n", eco.TestCmd)
			}
			if eco.LintCmd != "" {
				fmt.Fprintf(&b, "  - Lint: `%s`\n", eco.LintCmd)
			}
		}
		b.WriteString("\n")
	}

	return b.String()
}

// renderClaudeMD builds the root CLAUDE.md file read by Claude Code.
func renderClaudeMD(a Analysis) string {
	var b strings.Builder
	b.WriteString("# CLAUDE.md\n\n")
	b.WriteString("This file gives Claude Code project-specific context and conventions.\n")
	b.WriteString("Generated by `repomap agents` from the current repository structure — edit freely to add real conventions, gotchas, and preferences.\n\n")
	b.WriteString(overviewBody(a))
	b.WriteString("## Working agreements\n\n")
	b.WriteString("- Prefer editing existing files over creating new ones.\n")
	b.WriteString("- Match the existing code style in each language/directory rather than introducing new conventions.\n")
	b.WriteString("- Run the relevant build/test/lint commands above before considering a change complete.\n")
	return b.String()
}

// renderClaudeSkill builds a Claude Code SKILL.md that orients an agent to
// this repository's layout when the skill is invoked.
func renderClaudeSkill(a Analysis) string {
	var b strings.Builder
	slug := slugify(a.ProjectName) + "-overview"
	desc := fmt.Sprintf("Use when working in the %s repository and you need a refresher on its layout, languages, and build/test commands.", a.ProjectName)

	b.WriteString("---\n")
	fmt.Fprintf(&b, "name: %s\n", slug)
	fmt.Fprintf(&b, "description: %s\n", desc)
	b.WriteString("---\n\n")
	b.WriteString(overviewBody(a))
	b.WriteString("Use this context to navigate the repository before making changes; re-run `repomap agents` after significant structural changes to refresh it.\n")
	return b.String()
}

// claudeSettings mirrors the shape of .claude/settings.json's permissions
// block (only the fields this tool populates).
type claudeSettings struct {
	Permissions struct {
		Allow []string `json:"allow"`
		Deny  []string `json:"deny"`
	} `json:"permissions"`
}

// renderClaudeSettings builds .claude/settings.json: a permissions allowlist
// derived from the repository's detected ecosystems, so Claude Code doesn't
// prompt for routine build/test/lint/git-inspection commands. Destructive
// git operations and arbitrary shell stay gated regardless of ecosystem.
func renderClaudeSettings(a Analysis) string {
	allow := []string{
		"Bash(git status*)",
		"Bash(git diff*)",
		"Bash(git log*)",
		"Bash(git add*)",
		"Bash(find .*)",
		"Bash(ls*)",
	}

	seen := map[string]bool{}
	for _, eco := range a.Ecosystems {
		for _, cmd := range []string{eco.BuildCmd, eco.TestCmd, eco.LintCmd} {
			if cmd == "" {
				continue
			}
			rule := "Bash(" + commandPrefix(cmd) + "*)"
			if !seen[rule] {
				seen[rule] = true
				allow = append(allow, rule)
			}
		}
	}

	var s claudeSettings
	s.Permissions.Allow = allow
	s.Permissions.Deny = []string{
		"Bash(git push --force*)",
		"Bash(git push -f*)",
		"Bash(git reset --hard*)",
		"Bash(git clean -f*)",
		"Bash(git branch -D*)",
		"Bash(git checkout .*)",
		"Bash(git restore .*)",
		"Bash(rm -rf*)",
	}

	out, _ := json.MarshalIndent(s, "", "  ")
	return string(out) + "\n"
}

// commandPrefix reduces a shell command to its first two whitespace-separated
// tokens (e.g. "go test ./..." -> "go test"), used as a permission-rule
// prefix that still covers common flag variations of the same command.
func commandPrefix(cmd string) string {
	fields := strings.Fields(cmd)
	if len(fields) > 2 {
		fields = fields[:2]
	}
	return strings.Join(fields, " ")
}

// renderCopilotInstructions builds .github/copilot-instructions.md.
func renderCopilotInstructions(a Analysis) string {
	var b strings.Builder
	b.WriteString("# GitHub Copilot Instructions\n\n")
	b.WriteString("Generated by `repomap agents`. Copilot reads this file automatically for repository-wide context.\n\n")
	b.WriteString(overviewBody(a))
	return b.String()
}

// renderCursorRules builds .cursor/rules/repository.mdc.
func renderCursorRules(a Analysis) string {
	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString("description: Repository overview generated by repomap agents\n")
	b.WriteString("alwaysApply: true\n")
	b.WriteString("---\n\n")
	b.WriteString(overviewBody(a))
	return b.String()
}

// renderAgentsMD builds the generic AGENTS.md convention used by several
// AI coding tools (OpenAI Codex CLI, and others that follow the same
// convention) as a tool-agnostic fallback.
func renderAgentsMD(a Analysis) string {
	var b strings.Builder
	b.WriteString("# AGENTS.md\n\n")
	b.WriteString("Generic instructions for AI coding agents working in this repository.\n")
	b.WriteString("Generated by `repomap agents`; safe to hand-edit afterward.\n\n")
	b.WriteString(overviewBody(a))
	b.WriteString("## Guidelines\n\n")
	b.WriteString("- Keep changes scoped to what was asked.\n")
	b.WriteString("- Follow the build/test/lint commands above to validate changes before finishing.\n")
	return b.String()
}

var nonSlugChars = regexp.MustCompile(`[^a-z0-9]+`)

func slugify(s string) string {
	s = strings.ToLower(s)
	s = nonSlugChars.ReplaceAllString(s, "-")
	return strings.Trim(s, "-")
}
